#site config
name: Civic Auditorium
email: civic@smgov.net
baseurl: /csm-jekyll-test

#include definitions
primary_nav: primary-nav.html

local_css: 
  - /css/main.css

#jekyll build settings
markdown: kramdown

#defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
