#site config
name: Civic Auditorium
email: civic@smgov.net
phone: 310-458-8350
rentalphone: 310-458-4924
address: 1685 Main Street
city: Santa Monica
state: CA
zip: 90401

baseurl: /csm-jekyll-test
mapurl: https://goo.gl/maps/sDOrU

#include definitions
attribution: footer/attribution.html

localcss: 
  - /css/main.css

localjs:
  - /common/js/doubletaptogo.js
  - /js/nav-dropdown.js

#jekyll build settings
markdown: kramdown

#defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
